1_13_R2/pom.xml, 1_13_R2/src/main/java/net/wesjd/anvilgui/version/Wrapper1_13_R2.java, api/src/main/java/net/wesjd/anvilgui/version/VersionMatcher.java
=> Updated for 1.13.1

1_14_R1/src/main/java/net/wesjd/anvilgui/version/Wrapper1_14_R1.java, api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java, api/src/main/java/net/wesjd/anvilgui/version/VersionMatcher.java
Fixed issue where there were no items in the inventory and you can't type anything.
=> Inventory fix

api/pom.xml
Thanks for adding the 1.14.4 support but I noticed it wasn't getting shaded into my jar.
=> Add 1_14_4 to api

api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java
Fix issue #58, no need to throw error.
=> No need to throw an error

1_12_R1/src/main/java/net/wesjd/anvilgui/version/Wrapper1_12_R1.java, 1_13_R1/src/main/java/net/wesjd/anvilgui/version/Wrapper1_13_R1.java, 1_13_R2/src/main/java/net/wesjd/anvilgui/version/Wrapper1_13_R2.java
Version corrections, add missing Javadoc.
=> Update a few Wrapper poms

README.md
The old jickpack site is showing wrong dependency(actually no but you know). The p.r. is showing people how to find the dependency.
(not fix, just realizing) Closes #86
=> People can't understand how to use jickpack.

1_16_R1/pom.xml, 1_16_R1/src/main/java/net/wesjd/anvilgui/version/Wrapper1_16_R1.java, api/pom.xml, api/src/main/java/net/wesjd/anvilgui/version/VersionMatcher.java, pom.xml
~~I have yet to test these changes, but it should work fine, as no big changes in that area happened.~~ It works
Fixes #93
=> Add wrapper class for 1.16

api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java
=> fixed inventory click event cancelling

1_16_R2/pom.xml, 1_16_R2/src/main/java/net/wesjd/anvilgui/version/Wrapper1_16_R2.java, api/pom.xml, api/src/main/java/net/wesjd/anvilgui/version/VersionMatcher.java, pom.xml
=> Add wrapper class for 1.16.2

1_10_R1/src/main/java/net/wesjd/anvilgui/version/Wrapper1_10_R1.java, 1_11_R1/src/main/java/net/wesjd/anvilgui/version/Wrapper1_11_R1.java, 1_12_R1/src/main/java/net/wesjd/anvilgui/version/Wrapper1_12_R1.java, 1_13_R1/src/main/java/net/wesjd/anvilgui/version/Wrapper1_13_R1.java, 1_13_R2/src/main/java/net/wesjd/anvilgui/version/Wrapper1_13_R2.java, 1_14_4_R1/src/main/java/net/wesjd/anvilgui/version/special/AnvilContainer1_14_4_R1.java, 1_14_R1/src/main/java/net/wesjd/anvilgui/version/Wrapper1_14_R1.java, 1_15_R1/src/main/java/net/wesjd/anvilgui/version/Wrapper1_15_R1.java, 1_16_R1/src/main/java/net/wesjd/anvilgui/version/Wrapper1_16_R1.java, 1_16_R2/src/main/java/net/wesjd/anvilgui/version/Wrapper1_16_R2.java, 1_7_R4/src/main/java/net/wesjd/anvilgui/version/Wrapper1_7_R4.java, 1_8_R1/src/main/java/net/wesjd/anvilgui/version/Wrapper1_8_R1.java, 1_8_R2/src/main/java/net/wesjd/anvilgui/version/Wrapper1_8_R2.java, 1_8_R3/src/main/java/net/wesjd/anvilgui/version/Wrapper1_8_R3.java, 1_9_R1/src/main/java/net/wesjd/anvilgui/version/Wrapper1_9_R1.java, 1_9_R2/src/main/java/net/wesjd/anvilgui/version/Wrapper1_9_R2.java
This just needs to be tested and then it can be merged. Should resolve #96.
=> Stop items from dropping from the inventory on server close

1_16_R3/pom.xml, 1_16_R3/src/main/java/net/wesjd/anvilgui/version/Wrapper1_16_R3.java, api/pom.xml, api/src/main/java/net/wesjd/anvilgui/version/VersionMatcher.java, pom.xml
add wrapper class for the new nms package 1_16_R3 (spigot 1.16.4). Tested.
=> Add wrapper class for 1_16_R3 / spigot 1.16.4

1_10_R1/pom.xml, 1_11_R1/pom.xml, 1_12_R1/pom.xml, 1_13_R1/pom.xml, 1_13_R2/pom.xml, 1_14_4_R1/pom.xml, 1_14_R1/pom.xml, 1_15_R1/pom.xml, 1_16_R1/pom.xml, 1_16_R2/pom.xml, 1_16_R3/pom.xml, 1_17_R1/pom.xml, 1_7_R4/pom.xml, 1_8_R1/pom.xml, 1_8_R2/pom.xml, 1_8_R3/pom.xml, 1_9_R1/pom.xml, 1_9_R2/pom.xml, README.md, abstraction/pom.xml, api/pom.xml, api/src/main/java/net/wesjd/anvilgui/version/VersionMatcher.java, pom.xml
This changes version matcher to fix issue #165
=> New version matcher to fix #165

1_17_1_R1/pom.xml, 1_17_1_R1/src/main/java/net/wesjd/anvilgui/version/special/AnvilContainer1_17_1_R1.java, 1_17_R1/src/main/java/net/wesjd/anvilgui/version/Wrapper1_17_R1.java, api/pom.xml, pom.xml
Add anvil container for 1.17.1 to fix #160
=> Fix XP issue for 1.17.1

README.md
Added note to prevent users from setting <minimizeJar> to true.
This closes #190
=> Add minimizeJar warning

api/pom.xml
Add 1.19.1 special wrapper to api dep.
=> Include 1_19_1_R1 as dependency

1_19_R1/src/main/java/net/wesjd/anvilgui/version/Wrapper1_19_R1.java
#226 won't work, this will *probably*, and it is a lot simpler.
=> 1.19.2 Support

api/pom.xml
#251 and #252 weren't identical enough.
=> Add dependency on 1.19.4 module to the API module

1_10_R1/pom.xml, 1_11_R1/pom.xml, 1_12_R1/pom.xml, 1_13_R1/pom.xml, 1_13_R2/pom.xml, 1_14_4_R1/pom.xml, 1_14_R1/pom.xml, 1_15_R1/pom.xml, 1_16_R1/pom.xml, 1_16_R2/pom.xml, 1_16_R3/pom.xml, 1_17_1_R1/pom.xml, 1_17_R1/pom.xml, 1_18_R1/pom.xml, 1_18_R2/pom.xml, 1_19_1_R1/pom.xml, 1_19_R1/pom.xml, 1_19_R2/pom.xml, 1_19_R3/pom.xml, 1_7_R4/pom.xml, 1_8_R1/pom.xml, 1_8_R2/pom.xml, 1_8_R3/pom.xml, 1_9_R1/pom.xml, 1_9_R2/pom.xml, abstraction/pom.xml, api/pom.xml, api/src/main/java/net/wesjd/anvilgui/AnvilGUI.java, pom.xml
Should we handle it like this, or rename the left input slot in place instead?
Fixes #262
=> Fix NPE when using replaceInputText

1_20_R1/pom.xml, 1_20_R1/src/main/java/net.wesjd.anvilgui.version/Wrapper1_20_R1.java, api/pom.xml, pom.xml
This should work (but does compile), but I didn't and can't test it thoroughly.
We'll first have to wait for codemc to host the binary jar though, but you can get it locally through the Spigot BuildTools.
=> Add: Support for 1.20

README.md
=> Correct error in shading guide
